# Generated by Django 6.0.4 on 2026-04-09 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('industrytype', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=20)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.CharField(max_length=500)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('companyname', models.CharField(max_length=100)),
                ('rating', models.FloatField()),
                ('comment', models.CharField(max_length=500)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='freelancer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('skills', models.CharField(max_length=200)),
                ('contact', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('rating', models.FloatField()),
                ('count', models.IntegerField()),
                ('education', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='projectcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryname', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='questionnaire',
            fields=[
                ('questionid', models.AutoField(primary_key=True, serialize=False)),
                ('categoryname', models.CharField(max_length=100)),
                ('question', models.CharField(max_length=200)),
                ('option1', models.CharField(max_length=100)),
                ('option2', models.CharField(max_length=100)),
                ('option3', models.CharField(max_length=100)),
                ('option4', models.CharField(max_length=100)),
                ('answer', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='freelancerexperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyname', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=100)),
                ('projecthandled', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('freelancername', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skilllinkapp.freelancer')),
            ],
        ),
        migrations.CreateModel(
            name='paymentfreelancer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upi_id', models.CharField(max_length=100)),
                ('bankname', models.CharField(max_length=100)),
                ('accountnumber', models.CharField(max_length=20)),
                ('ifsc', models.CharField(max_length=20)),
                ('mode', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='')),
                ('upiform', models.CharField(max_length=50)),
                ('freelancername', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skilllinkapp.freelancer')),
            ],
        ),
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('requiredskills', models.CharField(max_length=200)),
                ('budget', models.FloatField()),
                ('duration', models.CharField(max_length=100)),
                ('postedat', models.DateTimeField(auto_now_add=True)),
                ('companyname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skilllinkapp.company')),
            ],
        ),
        migrations.CreateModel(
            name='paymentcompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('commission', models.FloatField()),
                ('paymentdate', models.DateTimeField(auto_now_add=True)),
                ('paymentmode', models.CharField(max_length=100)),
                ('freelancername', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skilllinkapp.freelancer')),
                ('projectname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skilllinkapp.project')),
            ],
        ),
        migrations.CreateModel(
            name='notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=200)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('companyname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skilllinkapp.company')),
                ('freelancername', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skilllinkapp.freelancer')),
                ('projectname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skilllinkapp.project')),
            ],
        ),
        migrations.CreateModel(
            name='bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidamount', models.FloatField()),
                ('duration', models.CharField(max_length=100)),
                ('biddate', models.DateTimeField(auto_now_add=True)),
                ('freelancername', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skilllinkapp.freelancer')),
                ('projectname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skilllinkapp.project')),
            ],
        ),
        migrations.CreateModel(
            name='allotment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startdate', models.DateTimeField(auto_now_add=True)),
                ('allotdate', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=100)),
                ('rating', models.FloatField()),
                ('companyname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skilllinkapp.company')),
                ('freelancername', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skilllinkapp.freelancer')),
                ('projectname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skilllinkapp.project')),
            ],
        ),
        migrations.CreateModel(
            name='quizresult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryname', models.CharField(max_length=100)),
                ('score', models.FloatField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('freelancername', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skilllinkapp.freelancer')),
                ('questionid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skilllinkapp.questionnaire')),
            ],
        ),
    ]
