# Generated by Django 6.0.4 on 2026-04-13 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skilllinkapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freelancer',
            name='location',
        ),
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='freelancer',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='freelancer',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
    ]
