# Generated by Django 6.0.4 on 2026-04-16 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skilllinkapp', '0002_alter_enquiry_message'),
        ('skilllinkapp', '0002_remove_freelancer_location_alter_company_email_and_more'),
    ]

    operations = [
    ]
