# Generated by Django 6.0.4 on 2026-04-16 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skilllinkapp', '0003_merge_20260416_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='duration',
            field=models.TextField(),
        ),
    ]
