# Generated by Django 6.0.4 on 2026-04-20 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skilllinkapp', '0004_alter_project_duration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='freelancer',
            old_name='contact',
            new_name='mobile',
        ),
    ]
