# Generated by Django 6.0.4 on 2026-04-23 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skilllinkapp', '0005_rename_contact_freelancer_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='proposal',
            field=models.TextField(default=''),
        ),
    ]
