# Generated by Django 6.0.4 on 2026-04-24 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skilllinkapp', '0006_bid_proposal'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_selected',
            field=models.BooleanField(default=False),
        ),
    ]
