# Generated by Django 6.0.4 on 2026-04-27 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skilllinkapp', '0007_project_is_selected'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='is_selected',
            field=models.BooleanField(default=False),
        ),
    ]
