# Generated by Django 6.0.4 on 2026-04-28 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skilllinkapp', '0008_bid_is_selected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allotment',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
    ]
